### ISSUE TITLE
Changing brightness with mouse wheel

### ISSUE THREAD

**Issue by muzena** [cardsurf/brightness-and-gamma-applet#1]
Hello @cardsurf 
Can you add option in applet for changing brightness with mouse wheel scrolling over applet icon?

**Comment by cardsurf** [comment]
Yes. I will add this feature in the upcoming days.

**Comment by cardsurf** [comment]
This feature has been implemented. It is available in the Linux Mint Cinnamon Applets repostiory and will be a part of the next applet release.

**Comment by muzena** [comment]
Thanks

**Comment by muzena** [comment]
@cardsurf 
Applet dosen't work anymore in Cinnamon 3.4

**Comment by cardsurf** [comment]
Thank you very much for the information. I have made a pull request to the Linux Mint Cinnamon Applets repository that fixes the issue.
